name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Git identity
        run: |
          git config --global user.name "aekapong"
          git config --global user.email "aekapong.saeya@gmail.com"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          allow_empty_commit: true   # ถ้าไม่มีอะไรเปลี่ยนก็ไม่ error
